"""migration 2

Revision ID: 1481eeeb24e3
Revises: 528e7fc6c834
Create Date: 2024-03-31 16:54:15.300306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1481eeeb24e3'
down_revision: Union[str, None] = '528e7fc6c834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculums', sa.Column('Address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculums', 'Address')
    # ### end Alembic commands ###
